/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Company.Company;

/**
 *
 * @author HP
 */
public class MainWindow extends javax.swing.JFrame {

    
    private Company nickelodeon;
    private Company DisneyChannel;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
//        this.tabPanel.addTab("Disney", new Disney(this.getNickelodeon()));
        this.tabPanel.addTab("Welcome", new Welcome());
       
        this.tabPanel.addTab("Settings", new Settings());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPanel.setBackground(new java.awt.Color(239, 248, 226));
        tabPanel.setForeground(new java.awt.Color(2, 4, 15));
        tabPanel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 14)); // NOI18N
        tabPanel.setMaximumSize(new java.awt.Dimension(900, 700));
        tabPanel.setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().add(tabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nickelodeon
     */
    public Company getNickelodeon() {
        return nickelodeon;
    }

    /**
     * @param nickelodeon the nickelodeon to set
     */
    public void setNickelodeon(Company nickelodeon) {
        this.nickelodeon = nickelodeon;
    }

    /**
     * @return the DisneyChannel
     */
    public Company getDisneyChannel() {
        return DisneyChannel;
    }

    /**
     * @param DisneyChannel the DisneyChannel to set
     */
    public void setDisneyChannel(Company DisneyChannel) {
        this.DisneyChannel = DisneyChannel;
    }

    /**
     * @return the tabPanel
     */
    public javax.swing.JTabbedPane getTabPanel() {
        return tabPanel;
    }

    /**
     * @param tabPanel the tabPanel to set
     */
    public void setTabPanel(javax.swing.JTabbedPane tabPanel) {
        this.tabPanel = tabPanel;
    }
}
