/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author andre
 */
public class Welcome extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        iniciarDisney = new javax.swing.JButton();
        iniciarNick1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 248, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(239, 248, 226));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(2, 4, 15));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("El siguiente programa ejecuta una simulación de la operación de una sede de animación para Disney Channel y Nickelodeon en Venezuela. \nNavega las ventanas para acceder a todas las funcionalidades de la simulación !");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 530, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/titleIcon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 560, 360));

        iniciarDisney.setBackground(new java.awt.Color(239, 248, 226));
        iniciarDisney.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        iniciarDisney.setForeground(new java.awt.Color(0, 107, 153));
        iniciarDisney.setText("Iniciar Disney");
        iniciarDisney.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 107, 153), 3, true));
        iniciarDisney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarDisneyActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 140, 30));

        iniciarNick1.setBackground(new java.awt.Color(239, 248, 226));
        iniciarNick1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        iniciarNick1.setForeground(new java.awt.Color(245, 125, 13));
        iniciarNick1.setText("Iniciar Nickelodeon");
        iniciarNick1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 125, 13), 3, true));
        iniciarNick1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarNick1ActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarNick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 140, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarNick1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarNick1ActionPerformed
        Starter.startSimNickelodeon();
    }//GEN-LAST:event_iniciarNick1ActionPerformed

    private void iniciarDisneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarDisneyActionPerformed
         Starter.startSimDisney();
    }//GEN-LAST:event_iniciarDisneyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarDisney;
    private javax.swing.JButton iniciarNick1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
